# Load up files for Framingham Heart Study
framingham <- read.csv("Framingham.csv")
str(framingham)
# Last variable is the outcome of the dataset (heart disease or not)
library("caTools")
set.seed(1000)
split <- sample.split(framingham$TenYearCHD, SplitRatio = 0.65)
train <- subset(framingham, split == T)
test <- subset(framingham, split == F)
framinghamLog <- glm(TenYearCHD ~ ., data = train, family = binomial)
summary(framinghamLog)
predictTest <- predict(framinghamLog, type = "response", newdata = test)
table(test$TenYearCHD, predictTest > 0.5)
library(ROCR)
ROCRpred <- prediction(predictTest, test$TenYearCHD)
as.numeric(performance(ROCRpred,"auc")@y.values) # AUC value AKA integral of ROCR curve
